[build-system]
requires = [
"argparse",
"tabulate",
"setuptools",
"wheel"
]
build-backend = "setuptools.build_meta"


[tool.setuptools.packages.find]
where = ["magv"]

[tool.setuptools.package-data]
mypkg = ["*.json"]